"""Mock LLM provider for testing and CI.

Provides deterministic responses without requiring API keys or network access.
"""

from typing import Any, Dict, List, Optional

from .base import BaseLLMProvider


class MockLLMProvider(BaseLLMProvider):
    """Deterministic provider for tests and CI. No network required."""

    def __init__(self, api_key: str = "mock", config: Dict[str, Any] = None):
        """Initialize mock provider.

        Args:
            api_key: Ignored for mock provider (defaults to "mock")
            config: Optional configuration dict (ignored for mock provider)
        """
        # Don't call super().__init__ to avoid requiring api_key validation
        self.api_key = api_key
        self.config = config or {}
        self.model = "mock-model"
        self.max_tokens = 4096
        self.temperature = 0.0  # Deterministic

    def generate(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        """Generate deterministic mock response.

        Args:
            prompt: User prompt (content is analyzed for context)
            system_prompt: Optional system prompt (ignored)

        Returns:
            Deterministic mock response
        """
        # Return a simple deterministic response
        return (
            "This is a mock response for testing. "
            "The actual content is generated deterministically."
        )

    def generate_code(
        self,
        description: str,
        file_type: str,
        context: Optional[Dict[str, Any]] = None,
        images: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """Generate mock code based on file type.

        Args:
            description: Description of what the code should do
            file_type: Type of file (e.g., 'php', 'css', 'js')
            context: Additional context (ignored)
            images: Optional image data (ignored)

        Returns:
            Mock code appropriate for the file type
        """
        context = context or {}
        theme_name = context.get("theme_name", "wpgen-test-theme")

        if file_type == "style.css" or file_type == "css":
            return (
                "/*\n"
                f"Theme Name: {theme_name.replace('-', ' ').title()}\n"
                "Author: WPGen CI\n"
                "Version: 0.0.1\n"
                "Description: Minimal theme for CI testing\n"
                "*/\n\n"
                "body {\n"
                "    font-family: sans-serif;\n"
                "    margin: 0;\n"
                "    padding: 0;\n"
                "}\n"
            )
        elif file_type == "functions.php" or file_type == "php":
            return (
                "<?php\n"
                "/**\n"
                f" * Theme functions for {theme_name}\n"
                " * Generated by WPGen Mock Provider\n"
                " */\n\n"
                "// Theme setup\n"
                "function wpgen_theme_setup() {\n"
                "    add_theme_support('title-tag');\n"
                "    add_theme_support('post-thumbnails');\n"
                "}\n"
                "add_action('after_setup_theme', 'wpgen_theme_setup');\n"
            )
        elif file_type == "index.php":
            return (
                "<?php\n"
                "/**\n"
                f" * Main template file for {theme_name}\n"
                " */\n"
                "get_header();\n"
                "?>\n\n"
                "<main>\n"
                "    <h1>Mock Theme</h1>\n"
                "    <p>This is a mock theme for testing.</p>\n"
                "</main>\n\n"
                "<?php\n"
                "get_footer();\n"
            )
        elif file_type == "header.php":
            return (
                "<!DOCTYPE html>\n"
                "<html <?php language_attributes(); ?>>\n"
                "<head>\n"
                "    <meta charset=\"<?php bloginfo('charset'); ?>\">\n"
                "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                "    <?php wp_head(); ?>\n"
                "</head>\n"
                "<body <?php body_class(); ?>>\n"
                "<?php wp_body_open(); ?>\n"
                "<header>\n"
                "    <h1><?php bloginfo('name'); ?></h1>\n"
                "</header>\n"
            )
        elif file_type == "footer.php":
            return (
                "<footer>\n"
                "    <p>&copy; <?php echo date('Y'); ?> "
                "<?php bloginfo('name'); ?></p>\n"
                "</footer>\n"
                "<?php wp_footer(); ?>\n"
                "</body>\n"
                "</html>\n"
            )
        else:
            # Generic file content
            return f"/* Mock content for {file_type} */\n"

    def analyze_prompt(self, prompt: str) -> Dict[str, Any]:
        """Analyze prompt and return deterministic requirements.

        Args:
            prompt: Natural language description

        Returns:
            Dictionary with theme requirements
        """
        # Extract theme name from prompt if possible, otherwise use default
        theme_name = "wpgen-test-theme"
        if "theme" in prompt.lower():
            # Simple extraction - in real provider this would be more sophisticated
            words = prompt.lower().split()
            if "blog" in words:
                theme_name = "wpgen-blog-theme"
            elif "business" in words:
                theme_name = "wpgen-business-theme"
            elif "portfolio" in words:
                theme_name = "wpgen-portfolio-theme"

        return {
            "theme_name": theme_name,
            "theme_display_name": theme_name.replace("-", " ").title(),
            "description": "Deterministic theme for CI testing",
            "features": ["responsive", "accessible", "seo-friendly"],
            "color_scheme": {
                "primary": "#0073aa",
                "secondary": "#23282d",
                "text": "#32373c",
                "background": "#ffffff",
            },
            "pages": ["home", "about", "contact"],
            "post_types": ["post", "page"],
            "files": [
                "style.css",
                "functions.php",
                "index.php",
                "header.php",
                "footer.php",
                "single.php",
                "page.php",
            ],
        }

    def analyze_image(self, image_data: Dict[str, Any], prompt: str) -> Dict[str, Any]:
        """Mock image analysis (vision not supported in mock).

        Args:
            image_data: Image data dict
            prompt: Analysis prompt

        Returns:
            Mock analysis result
        """
        return {
            "analysis": "Mock image analysis",
            "colors": ["#0073aa", "#ffffff"],
            "layout": "standard",
            "elements": ["header", "content", "footer"],
        }

    def analyze_prompt_multimodal(
        self,
        prompt: str,
        images: Optional[List[Dict[str, Any]]] = None,
        additional_context: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Analyze prompt with multimodal inputs (mock implementation).

        Args:
            prompt: Natural language description
            images: Optional image data (ignored in mock)
            additional_context: Optional additional context

        Returns:
            Dictionary with theme requirements
        """
        # Base analysis
        result = self.analyze_prompt(prompt)

        # Add context if provided
        if additional_context:
            result["additional_context"] = "Mock context processed"

        if images:
            result["images_processed"] = len(images)

        return result

    def validate_api_key(self) -> bool:
        """Mock API key is always valid.

        Returns:
            Always True for mock provider
        """
        return True
