"""WordPress theme code generator.

This module generates complete WordPress themes based on parsed requirements.
It creates all necessary files including style.css, functions.php, templates, etc.
"""

import os
import re
import shutil
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime
from PIL import Image, ImageDraw, ImageFont

from ..llm.base import BaseLLMProvider
from ..utils.logger import get_logger
from ..utils.code_validator import validate_php_syntax, get_fallback_functions_php, get_fallback_template


logger = get_logger(__name__)


def _ensure_style_header(theme_dir: str, requirements: dict) -> None:
    """Ensure style.css has a valid WordPress theme header.

    Args:
        theme_dir: Path to theme directory
        requirements: Theme requirements dict
    """
    style_path = os.path.join(theme_dir, "style.css")
    theme_name = (requirements.get("theme_display_name")
                  or requirements.get("theme_name") or "WPGen Theme")

    # Ensure theme_name is a string
    if not isinstance(theme_name, str):
        theme_name = str(theme_name) if theme_name else "WPGen Theme"

    slug = (requirements.get("slug") or theme_name).lower()

    # Ensure slug is a string (defensive check)
    if not isinstance(slug, str):
        slug = str(slug) if slug else "wpgen-theme"
        slug = slug.lower()

    text_domain = re.sub(r"[^a-z0-9-]+", "-", slug)

    header = f"""/*
Theme Name: {theme_name}
Theme URI: https://wpgen.local/
Author: WPGen
Author URI: https://wpgen.local/
Description: Theme generated by WPGen.
Version: 0.1.0
Text Domain: {text_domain}
*/"""

    if not os.path.exists(style_path):
        with open(style_path, "w", encoding="utf-8") as f:
            f.write(header + "\n\n/* Add theme styles below */\n")
        return

    original = open(style_path, "r", encoding="utf-8", errors="ignore").read()
    trimmed = original.lstrip()
    has_header = trimmed.startswith("/*") and "Theme Name:" in trimmed.split("*/", 1)[0]
    if not has_header:
        with open(style_path, "w", encoding="utf-8") as f:
            f.write(header + "\n\n" + original)


def _first_hex(color_scheme: Optional[str], fallback: str = "#0f172a") -> str:
    """Extract first hex color from color scheme string.

    Args:
        color_scheme: Color scheme string that may contain hex colors
        fallback: Default color if none found

    Returns:
        First hex color found or fallback
    """
    if not color_scheme:
        return fallback

    # Ensure color_scheme is a string (defensive check)
    if not isinstance(color_scheme, str):
        logger.warning(f"color_scheme is not a string: {type(color_scheme).__name__}, using fallback")
        return fallback

    m = re.search(r"#([0-9a-fA-F]{6})", color_scheme)
    return f"#{m.group(1)}" if m else fallback


def _ensure_screenshot(theme_dir: str, requirements: dict, images: Optional[List[Dict[str, Any]]]) -> None:
    """Ensure theme has a screenshot.png file.

    Creates a screenshot from the first user image or generates a placeholder.

    Args:
        theme_dir: Path to theme directory
        requirements: Theme requirements dict
        images: List of image dicts with 'path' key, or None
    """
    shot_path = os.path.join(theme_dir, "screenshot.png")
    if os.path.exists(shot_path):
        return

    # Try to use first uploaded image as screenshot
    if images and len(images) > 0:
        try:
            # Images are dicts with 'path', 'data', 'mime_type' etc
            img_data = images[0]
            if isinstance(img_data, dict):
                src = img_data.get('path')
                if not src:
                    logger.warning("Image dict has no 'path' key, falling back to placeholder")
                    raise ValueError("No path in image data")
            else:
                src = img_data

            # Verify path exists
            if not os.path.exists(src):
                logger.warning(f"Image path does not exist: {src}")
                raise FileNotFoundError(f"Image not found: {src}")

            with Image.open(src) as im:
                im = im.convert("RGB")
                canvas = Image.new("RGB", (1200, 900), (247, 248, 250))
                r = im.copy()
                r.thumbnail((1200, 900))
                x = (1200 - r.width) // 2
                y = (900 - r.height) // 2
                canvas.paste(r, (x, y))
                canvas.save(shot_path, format="PNG", optimize=True)
                logger.info(f"Generated screenshot from uploaded image: {os.path.basename(src)}")
                return
        except Exception as e:
            logger.warning(f"Could not use uploaded image for screenshot: {e}. Generating placeholder instead.")

    # Generate placeholder screenshot
    title = (requirements.get("theme_display_name")
             or requirements.get("theme_name") or "WPGen Theme")
    primary = _first_hex(requirements.get("color_scheme"), "#0f172a")
    bg = (248, 250, 252)
    fg = tuple(int(primary.strip("#")[i:i+2], 16) for i in (0, 2, 4))
    img = Image.new("RGB", (1200, 900), bg)
    draw = ImageDraw.Draw(img)
    draw.rectangle([0, 600, 1200, 900], fill=fg)
    try:
        font_title = ImageFont.truetype("DejaVuSans-Bold.ttf", 64)
        font_sub = ImageFont.truetype("DejaVuSans.ttf", 28)
    except Exception:
        font_title = ImageFont.load_default()
        font_sub = ImageFont.load_default()
    bbox = draw.textbbox((0, 0), title, font=font_title)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text(((1200 - tw)//2, 330), title, fill=(17, 24, 39), font=font_title)
    sub = "Generated by WPGen"
    bbox2 = draw.textbbox((0, 0), sub, font=font_sub)
    sw, sh = bbox2[2] - bbox2[0], bbox2[3] - bbox2[1]
    draw.text(((1200 - sw)//2, 410), sub, fill=(55, 65, 81), font=font_sub)
    img.save(shot_path, format="PNG", optimize=True)
    logger.info("Generated placeholder screenshot")


class WordPressGenerator:
    """Generator for WordPress theme code."""

    def __init__(
        self,
        llm_provider: BaseLLMProvider,
        output_dir: str = "output",
        config: Dict[str, Any] = None,
    ):
        """Initialize the WordPress generator.

        Args:
            llm_provider: LLM provider for code generation
            output_dir: Base output directory for generated themes
            config: WordPress configuration from config.yaml
        """
        self.llm_provider = llm_provider
        self.output_dir = Path(output_dir)
        self.config = config or {}
        self.safe_mode = self.config.get("safe_mode", False)

        if self.safe_mode:
            logger.warning("⚠️  SAFE MODE ENABLED - Using only validated fallback templates")

        logger.info(f"Initialized WordPressGenerator with output dir: {output_dir}")

    def generate(
        self, requirements: Dict[str, Any], images: Optional[List[Dict[str, Any]]] = None
    ) -> str:
        """Generate a complete WordPress theme from requirements with optional visual references.

        Args:
            requirements: Parsed theme requirements
            images: Optional list of design mockup images for vision-based generation

        Returns:
            Path to the generated theme directory

        Raises:
            Exception: If generation fails
        """
        theme_name = requirements["theme_name"]
        logger.info(f"Starting theme generation: {theme_name}")

        # Store images for use in code generation methods
        self.design_images = images if images else None
        if self.design_images:
            logger.info(
                f"Using {len(self.design_images)} design reference image(s) for visual guidance"
            )

        # Create theme directory
        theme_dir = self.output_dir / theme_name
        if theme_dir.exists() and self.config.get("clean_before_generate", False):
            logger.warning(f"Cleaning existing theme directory: {theme_dir}")
            shutil.rmtree(theme_dir)

        theme_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"Created theme directory: {theme_dir}")

        try:
            # Generate core files
            self._generate_style_css(theme_dir, requirements)
            self._generate_functions_php(theme_dir, requirements)
            self._generate_index_php(theme_dir, requirements)
            self._generate_header_php(theme_dir, requirements)
            self._generate_footer_php(theme_dir, requirements)
            self._generate_sidebar_php(theme_dir, requirements)

            # Generate template files
            self._generate_templates(theme_dir, requirements)

            # Generate always-on UI enhancements (smooth transitions, mobile nav)
            self._generate_wpgen_ui_assets(theme_dir)

            # Generate optional features (if specified in requirements/context)
            self._generate_optional_features(theme_dir, requirements)

            # Generate additional files
            self._generate_readme(theme_dir, requirements)
            self._generate_gitignore(theme_dir)

            # Generate wp-config sample if requested
            if self.config.get("include_wp_config", True):
                self._generate_wp_config(theme_dir.parent, requirements)

            # Ensure theme identity (style header + screenshot)
            _ensure_style_header(str(theme_dir), requirements)
            _ensure_screenshot(str(theme_dir), requirements, images)
            logger.info("✓ Theme thumbnail prepared (screenshot.png)")

            logger.info(f"Successfully generated theme: {theme_name}")
            return str(theme_dir)

        except Exception as e:
            logger.error(f"Failed to generate theme: {str(e)}")
            raise

    def _generate_style_css(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate style.css file with theme header and styles.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements
        """
        logger.info("Generating style.css")

        # Generate the header comment
        author = self.config.get("author", "WPGen")
        license = self.config.get("license", "GPL-2.0-or-later")
        version = "1.0.0"
        wp_version = self.config.get("wp_version", "6.4")

        header = f"""/*
Theme Name: {requirements['theme_display_name']}
Theme URI: https://github.com/yourusername/{requirements['theme_name']}
Author: {author}
Author URI: https://github.com/yourusername
Description: {requirements['description']}
Version: {version}
Requires at least: {wp_version}
Tested up to: {wp_version}
Requires PHP: 7.4
License: {license}
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: {requirements['theme_name']}
Tags: {', '.join(requirements.get('features', [])[:5])}
*/

"""

        # Generate CSS using LLM
        context = {
            "theme_name": requirements["theme_name"],
            "color_scheme": requirements.get("color_scheme", "default"),
            "layout": requirements.get("layout", "full-width"),
            "features": requirements.get("features", []),
        }

        description = f"""Create a complete CSS stylesheet for a WordPress theme.
The theme should have a {context['color_scheme']} color scheme with {context['layout']} layout.
Include:
- Reset/normalize styles
- Typography (headings, paragraphs, links)
- Layout structure (header, main, sidebar, footer)
- Navigation menu styles
- Post/page content styles
- Widget styles
- Responsive design (mobile-first)
- Utility classes"""

        try:
            # Pass design images for visual reference (especially important for CSS styling)
            css_code = self.llm_provider.generate_code(
                description, "css", context, images=self.design_images
            )
            full_css = header + css_code

            style_file = theme_dir / "style.css"
            style_file.write_text(full_css, encoding="utf-8")
            logger.info("Generated style.css successfully")

        except Exception as e:
            logger.error(f"Failed to generate style.css: {str(e)}")
            # Write minimal fallback
            style_file = theme_dir / "style.css"
            style_file.write_text(header + "\n/* Add your styles here */\n", encoding="utf-8")

    def _generate_functions_php(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate functions.php file.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements
        """
        logger.info("Generating functions.php")

        # SAFE MODE: Always use fallback
        if self.safe_mode:
            logger.info("Safe mode: Using fallback functions.php")
            php_code = get_fallback_functions_php(requirements["theme_name"])
            functions_file = theme_dir / "functions.php"
            functions_file.write_text(php_code, encoding="utf-8")
            logger.info("Created safe-mode functions.php")
            return

        context = {
            "theme_name": requirements["theme_name"],
            "features": requirements.get("features", []),
            "navigation": requirements.get("navigation", []),
            "post_types": requirements.get("post_types", []),
            "integrations": requirements.get("integrations", []),
        }

        description = f"""Create a complete functions.php file for a WordPress theme.
Include:
- Theme setup function with theme support declarations
- Enqueue scripts and styles (MUST enqueue assets/css/wpgen-ui.css and assets/js/wpgen-ui.js)
- Register navigation menus: {', '.join(context['navigation'])}
- Register widget areas
- Custom post types: {', '.join(context['post_types'])}
- Theme customizer settings
- Helper functions
- Security best practices (sanitization, escaping)

IMPORTANT: Always enqueue the wpgen-ui assets:
wp_enqueue_style('wpgen-ui', get_template_directory_uri() . '/assets/css/wpgen-ui.css', array(), '1.0.0');
wp_enqueue_script('wpgen-ui', get_template_directory_uri() . '/assets/js/wpgen-ui.js', array(), '1.0.0', true);"""

        try:
            # Pass design images for visual reference
            php_code = self.llm_provider.generate_code(
                description, "php", context, images=self.design_images
            )

            # Ensure PHP opening tag
            if not php_code.strip().startswith("<?php"):
                php_code = "<?php\n" + php_code

            # Validate PHP syntax
            is_valid, error_msg = validate_php_syntax(php_code)
            if not is_valid:
                logger.error(f"Generated functions.php has syntax errors: {error_msg}")
                logger.warning("Using fallback functions.php template")
                php_code = get_fallback_functions_php(requirements["theme_name"])

            functions_file = theme_dir / "functions.php"
            functions_file.write_text(php_code, encoding="utf-8")
            logger.info("Generated functions.php successfully")

        except Exception as e:
            logger.error(f"Failed to generate functions.php: {str(e)}")
            logger.warning("Using fallback functions.php template")
            php_code = get_fallback_functions_php(requirements["theme_name"])
            functions_file = theme_dir / "functions.php"
            functions_file.write_text(php_code, encoding="utf-8")
            logger.info("Created fallback functions.php")

    def _validate_and_write_php(
        self, theme_dir: Path, filename: str, php_code: str, fallback_code: Optional[str] = None
    ) -> None:
        """Validate PHP code and write to file with fallback.

        Args:
            theme_dir: Theme directory path
            filename: Name of the PHP file
            php_code: Generated PHP code
            fallback_code: Optional fallback code if validation fails
        """
        # Ensure PHP opening tag
        if not php_code.strip().startswith("<?php"):
            php_code = "<?php\n" + php_code

        # Validate PHP syntax
        is_valid, error_msg = validate_php_syntax(php_code)
        if not is_valid:
            logger.error(f"Generated {filename} has syntax errors: {error_msg}")
            if fallback_code:
                logger.warning(f"Using fallback {filename} template")
                php_code = fallback_code
            else:
                logger.warning(f"No fallback available for {filename}, using generated code anyway")

        file_path = theme_dir / filename
        file_path.write_text(php_code, encoding="utf-8")
        logger.info(f"Written {filename} successfully")

    def _generate_index_php(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate index.php template file.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements
        """
        logger.info("Generating index.php")

        context = {
            "theme_name": requirements["theme_name"],
            "layout": requirements.get("layout", "full-width"),
        }

        description = """Create the main index.php template file for WordPress.
This is the fallback template. Include:
- get_header() call
- The WordPress loop
- Post title, content, meta
- Pagination
- get_sidebar() if applicable
- get_footer() call
Use modern WordPress template tags and best practices."""

        try:
            # Pass design images for layout/structure reference
            php_code = self.llm_provider.generate_code(
                description, "php", context, images=self.design_images
            )

            self._validate_and_write_php(theme_dir, "index.php", php_code)

        except Exception as e:
            logger.error(f"Failed to generate index.php: {str(e)}")
            # Use minimal fallback
            fallback = """<?php
get_header();

if ( have_posts() ) :
    while ( have_posts() ) : the_post();
        ?>
        <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
            <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
            <div class="entry-content">
                <?php the_content(); ?>
            </div>
        </article>
        <?php
    endwhile;
    the_posts_pagination();
endif;

get_footer();
"""
            self._validate_and_write_php(theme_dir, "index.php", fallback)

    def _generate_header_php(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate header.php template file.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements
        """
        logger.info("Generating header.php")

        context = {
            "theme_name": requirements["theme_name"],
            "navigation": requirements.get("navigation", []),
        }

        description = """Create header.php template for WordPress theme.
Include:
- DOCTYPE and opening HTML tags
- wp_head() call
- Site title/logo
- Primary navigation menu
- Mobile-responsive header
Follow WordPress coding standards."""

        try:
            # Pass design images for header layout/navigation reference
            php_code = self.llm_provider.generate_code(
                description, "php", context, images=self.design_images
            )

            # Special handling for header - might start with <!DOCTYPE
            if not php_code.strip().startswith("<!DOCTYPE") and not php_code.strip().startswith(
                "<?php"
            ):
                php_code = "<?php\n" + php_code

            self._validate_and_write_php(theme_dir, "header.php", php_code)

        except Exception as e:
            logger.error(f"Failed to generate header.php: {str(e)}")
            fallback = """<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<header class="site-header">
    <h1><a href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php bloginfo( 'name' ); ?></a></h1>
    <nav>
        <?php
        wp_nav_menu( array(
            'theme_location' => 'primary',
            'menu_class'     => 'primary-menu',
        ) );
        ?>
    </nav>
</header>
<main id="main" class="site-main">
"""
            self._validate_and_write_php(theme_dir, "header.php", fallback)

    def _generate_footer_php(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate footer.php template file.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements
        """
        logger.info("Generating footer.php")

        context = {"theme_name": requirements["theme_name"]}

        description = """Create footer.php template for WordPress theme.
Include:
- Footer widget areas
- Copyright notice
- wp_footer() call
- Closing body and html tags
Follow WordPress coding standards."""

        try:
            # Pass design images for footer layout reference
            php_code = self.llm_provider.generate_code(
                description, "php", context, images=self.design_images
            )

            self._validate_and_write_php(theme_dir, "footer.php", php_code)

        except Exception as e:
            logger.error(f"Failed to generate footer.php: {str(e)}")
            fallback = """</main>
<footer class="site-footer">
    <p>&copy; <?php echo date( 'Y' ); ?> <?php bloginfo( 'name' ); ?>. All rights reserved.</p>
</footer>
<?php wp_footer(); ?>
</body>
</html>
"""
            self._validate_and_write_php(theme_dir, "footer.php", fallback)

    def _generate_sidebar_php(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate sidebar.php template file.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements
        """
        logger.info("Generating sidebar.php")

        context = {"theme_name": requirements["theme_name"]}

        description = """Create sidebar.php template for WordPress theme.
Include:
- Check if sidebar is active
- Display dynamic sidebar
- Follow WordPress coding standards."""

        try:
            # Pass design images for sidebar layout reference
            php_code = self.llm_provider.generate_code(
                description, "php", context, images=self.design_images
            )

            fallback = get_fallback_template('sidebar.php', requirements["theme_name"])
            self._validate_and_write_php(theme_dir, "sidebar.php", php_code, fallback)

        except Exception as e:
            logger.error(f"Failed to generate sidebar.php: {str(e)}")
            fallback = get_fallback_template('sidebar.php', requirements["theme_name"])
            self._validate_and_write_php(theme_dir, "sidebar.php", fallback)

    def _generate_templates(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate additional template files based on requirements.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements
        """
        logger.info("Generating template files")

        templates_to_generate = {
            "single.php": "Single post template",
            "page.php": "Static page template",
            "archive.php": "Archive listing template",
            "search.php": "Search results template",
            "404.php": "404 error page template",
        }

        # Add custom page templates
        for page in requirements.get("pages", []):
            if page not in ["index", "single", "archive", "search", "404"]:
                template_file = f"page-{page}.php"
                templates_to_generate[template_file] = f"Custom page template for {page}"

        for template_file, description in templates_to_generate.items():
            try:
                logger.info(f"Generating {template_file}")

                context = {"theme_name": requirements["theme_name"], "template_type": template_file}

                full_description = f"""Create {template_file} for WordPress theme.
{description}. Include appropriate WordPress loop and template tags.
Follow WordPress template hierarchy and coding standards."""

                # Pass design images for all template files
                php_code = self.llm_provider.generate_code(
                    full_description, "php", context, images=self.design_images
                )

                # Get fallback template if available
                fallback = get_fallback_template(template_file, requirements["theme_name"])

                self._validate_and_write_php(theme_dir, template_file, php_code, fallback if fallback else None)
                logger.info(f"Generated {template_file} successfully")

            except Exception as e:
                logger.error(f"Failed to generate {template_file}: {str(e)}")
                # Use fallback template if available
                fallback = get_fallback_template(template_file, requirements["theme_name"])
                if fallback:
                    logger.warning(f"Using fallback template for {template_file}")
                    self._validate_and_write_php(theme_dir, template_file, fallback)
                else:
                    logger.warning(f"No fallback available for {template_file}, skipping")
                    continue

    def _generate_wpgen_ui_assets(self, theme_dir: Path) -> None:
        """Generate always-on UI enhancement assets (CSS/JS for transitions and mobile nav).

        Args:
            theme_dir: Theme directory path
        """
        logger.info("Generating wpgen-ui assets (smooth transitions, mobile nav)")

        # Create assets directories
        assets_dir = theme_dir / "assets"
        css_dir = assets_dir / "css"
        js_dir = assets_dir / "js"
        css_dir.mkdir(parents=True, exist_ok=True)
        js_dir.mkdir(parents=True, exist_ok=True)

        # Generate CSS for smooth transitions and mobile navigation
        css_content = """/* WPGen UI Enhancements - Always On */

/* Smooth page transitions */
body {
    opacity: 0;
    transition: opacity 0.3s ease-in-out;
}

body.wpgen-loaded {
    opacity: 1;
}

/* Smooth internal link transitions */
a {
    transition: color 0.2s ease, background-color 0.2s ease, border-color 0.2s ease;
}

/* Mobile-first, thumb-friendly navigation */
@media (max-width: 768px) {
    /* Minimum tap target size: 44x44px for touch */
    nav a,
    button,
    .menu-item a,
    .nav-link {
        min-height: 44px;
        min-width: 44px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        padding: 0.75rem 1rem;
    }

    /* Mobile menu toggle button */
    .mobile-menu-toggle {
        min-height: 44px;
        min-width: 44px;
        cursor: pointer;
        background: transparent;
        border: none;
        padding: 0.75rem;
        font-size: 1.5rem;
    }

    /* Mobile menu - hidden by default */
    .mobile-menu {
        display: none;
        flex-direction: column;
        width: 100%;
    }

    .mobile-menu.active {
        display: flex;
    }
}

/* Responsive typography and spacing */
@media (max-width: 768px) {
    body {
        font-size: 16px; /* Minimum for mobile readability */
    }

    /* Generous touch padding */
    input[type="submit"],
    input[type="button"],
    .button,
    .btn {
        min-height: 44px;
        padding: 0.75rem 1.5rem;
    }
}
"""

        css_file = css_dir / "wpgen-ui.css"
        css_file.write_text(css_content, encoding="utf-8")

        # Generate JS for page transitions and mobile menu toggle
        js_content = """/* WPGen UI Enhancements - Always On */
(function() {
    'use strict';

    // Smooth page load transition
    document.addEventListener('DOMContentLoaded', function() {
        document.body.classList.add('wpgen-loaded');
    });

    // Smooth page navigation (prefetch and fade)
    var links = document.querySelectorAll('a[href^="' + window.location.origin + '"]');
    links.forEach(function(link) {
        link.addEventListener('click', function(e) {
            var href = this.getAttribute('href');
            // Skip anchors, external links, and special links
            if (href.indexOf('#') === 0 || this.getAttribute('target') === '_blank') {
                return;
            }
            e.preventDefault();
            document.body.classList.remove('wpgen-loaded');
            setTimeout(function() {
                window.location.href = href;
            }, 300);
        });
    });

    // Mobile menu toggle
    var toggleBtn = document.querySelector('.mobile-menu-toggle');
    var mobileMenu = document.querySelector('.mobile-menu');

    if (toggleBtn && mobileMenu) {
        toggleBtn.addEventListener('click', function() {
            mobileMenu.classList.toggle('active');
            this.setAttribute('aria-expanded',
                mobileMenu.classList.contains('active') ? 'true' : 'false'
            );
        });

        // Close menu when clicking outside
        document.addEventListener('click', function(e) {
            if (!toggleBtn.contains(e.target) && !mobileMenu.contains(e.target)) {
                mobileMenu.classList.remove('active');
                toggleBtn.setAttribute('aria-expanded', 'false');
            }
        });
    }
})();
"""

        js_file = js_dir / "wpgen-ui.js"
        js_file.write_text(js_content, encoding="utf-8")

        logger.info("Generated wpgen-ui assets successfully")

    def _generate_optional_features(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate optional feature assets based on requirements.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements dict
        """
        # Check for WooCommerce support
        integrations = requirements.get("integrations", [])
        features = requirements.get("features", [])
        description = requirements.get("description", "").lower()

        # WooCommerce support
        if "woocommerce" in integrations or "woocommerce" in description:
            logger.info("Adding WooCommerce support")
            self._generate_woocommerce_support(theme_dir)

        # Custom Gutenberg blocks
        # Check for block keywords in description or features
        blocks_to_create = []
        if "featured_products" in description or "featured products" in description:
            blocks_to_create.append("featured_products")
        if "lifestyle_image" in description or "lifestyle image" in description:
            blocks_to_create.append("lifestyle_image")
        if "promo_banner" in description or "promo banner" in description:
            blocks_to_create.append("promo_banner")

        if blocks_to_create:
            logger.info(f"Adding custom Gutenberg blocks: {', '.join(blocks_to_create)}")
            self._generate_gutenberg_blocks(theme_dir, blocks_to_create)

        # Dark mode toggle
        if "dark" in description and "mode" in description or "dark/light" in description:
            logger.info("Adding dark mode toggle")
            self._generate_dark_mode(theme_dir, requirements)

        # Animated preloader
        if "preloader" in description or "loading logo" in description or "animated loading" in description:
            logger.info("Adding animated preloader")
            self._generate_preloader(theme_dir, requirements)

    def _generate_woocommerce_support(self, theme_dir: Path) -> None:
        """Add WooCommerce support files and templates."""
        # Create woocommerce.php template
        woo_template = """<?php
/**
 * WooCommerce template
 *
 * This template is used for all WooCommerce pages
 */

get_header();

if ( function_exists( 'woocommerce' ) ) :
    ?>
    <div class="woocommerce-wrapper">
        <?php woocommerce_content(); ?>
    </div>
    <?php
endif;

get_footer();
"""
        woo_file = theme_dir / "woocommerce.php"
        woo_file.write_text(woo_template, encoding="utf-8")
        logger.info("Created woocommerce.php template")

    def _generate_gutenberg_blocks(self, theme_dir: Path, blocks: List[str]) -> None:
        """Generate custom Gutenberg blocks scaffolding."""
        blocks_dir = theme_dir / "blocks"
        blocks_dir.mkdir(exist_ok=True)

        block_configs = {
            "featured_products": {
                "title": "Featured Products",
                "icon": "products",
                "category": "widgets"
            },
            "lifestyle_image": {
                "title": "Lifestyle Image",
                "icon": "format-image",
                "category": "media"
            },
            "promo_banner": {
                "title": "Promo Banner",
                "icon": "megaphone",
                "category": "widgets"
            }
        }

        for block_name in blocks:
            if block_name not in block_configs:
                continue

            config = block_configs[block_name]
            block_dir = blocks_dir / block_name
            block_dir.mkdir(exist_ok=True)

            # Create block.json
            block_json = {
                "$schema": "https://schemas.wp.org/trunk/block.json",
                "apiVersion": 2,
                "name": f"wpgen/{block_name}",
                "title": config["title"],
                "category": config["category"],
                "icon": config["icon"],
                "description": f"Display {config['title'].lower()}",
                "supports": {
                    "html": False
                },
                "textdomain": "wpgen",
                "editorScript": "file:./index.js",
                "editorStyle": "file:./editor.css",
                "style": "file:./style.css"
            }

            import json
            block_json_file = block_dir / "block.json"
            block_json_file.write_text(json.dumps(block_json, indent=2), encoding="utf-8")

            # Create minimal index.js
            index_js = f"""import {{ registerBlockType }} from '@wordpress/blocks';

registerBlockType('wpgen/{block_name}', {{
    edit: () => {{
        return <div className='wp-block-wpgen-{block_name}'>{config['title']} Block</div>;
    }},
    save: () => {{
        return <div className='wp-block-wpgen-{block_name}'>{config['title']}</div>;
    }}
}});
"""
            (block_dir / "index.js").write_text(index_js, encoding="utf-8")

            # Create empty CSS files
            (block_dir / "style.css").write_text(f"/* {config['title']} block styles */\n", encoding="utf-8")
            (block_dir / "editor.css").write_text(f"/* {config['title']} editor styles */\n", encoding="utf-8")

            logger.info(f"Created Gutenberg block: {block_name}")

    def _generate_dark_mode(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate dark mode toggle CSS and JS."""
        assets_dir = theme_dir / "assets"
        css_dir = assets_dir / "css"
        js_dir = assets_dir / "js"

        # CSS for dark mode
        dark_css = """/* Dark Mode Support */
:root {
    --bg-primary: #ffffff;
    --text-primary: #1a202c;
    --bg-secondary: #f7fafc;
    --text-secondary: #4a5568;
}

[data-theme="dark"] {
    --bg-primary: #1a202c;
    --text-primary: #f7fafc;
    --bg-secondary: #2d3748;
    --text-secondary: #cbd5e0;
}

body {
    background-color: var(--bg-primary);
    color: var(--text-primary);
    transition: background-color 0.3s ease, color 0.3s ease;
}

/* Dark mode toggle button */
.dark-mode-toggle {
    position: fixed;
    bottom: 20px;
    right: 20px;
    width: 50px;
    height: 50px;
    border-radius: 50%;
    background: var(--bg-secondary);
    border: 2px solid var(--text-secondary);
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 24px;
    z-index: 1000;
}

@media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
        --bg-primary: #1a202c;
        --text-primary: #f7fafc;
        --bg-secondary: #2d3748;
        --text-secondary: #cbd5e0;
    }
}
"""
        (css_dir / "dark-mode.css").write_text(dark_css, encoding="utf-8")

        # JS for dark mode toggle
        dark_js = """(function() {
    'use strict';

    // Check for saved theme preference or default to system preference
    const savedTheme = localStorage.getItem('theme');
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const theme = savedTheme || (prefersDark ? 'dark' : 'light');

    document.documentElement.setAttribute('data-theme', theme);

    // Create toggle button
    const toggleBtn = document.createElement('button');
    toggleBtn.className = 'dark-mode-toggle';
    toggleBtn.setAttribute('aria-label', 'Toggle dark mode');
    toggleBtn.innerHTML = theme === 'dark' ? '☀️' : '🌙';
    document.body.appendChild(toggleBtn);

    toggleBtn.addEventListener('click', function() {
        const currentTheme = document.documentElement.getAttribute('data-theme');
        const newTheme = currentTheme === 'dark' ? 'light' : 'dark';

        document.documentElement.setAttribute('data-theme', newTheme);
        localStorage.setItem('theme', newTheme);
        this.innerHTML = newTheme === 'dark' ? '☀️' : '🌙';
    });
})();
"""
        (js_dir / "dark-mode.js").write_text(dark_js, encoding="utf-8")
        logger.info("Generated dark mode toggle")

    def _generate_preloader(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate animated preloader HTML/CSS/JS."""
        assets_dir = theme_dir / "assets"
        css_dir = assets_dir / "css"
        js_dir = assets_dir / "js"

        # CSS for preloader
        preloader_css = """/* Animated Preloader */
.wpgen-preloader {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: #ffffff;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 9999;
    transition: opacity 0.5s ease;
}

.wpgen-preloader.fade-out {
    opacity: 0;
    pointer-events: none;
}

.wpgen-preloader-logo {
    width: 80px;
    height: 80px;
    border: 4px solid #f3f4f6;
    border-top-color: #3b82f6;
    border-radius: 50%;
    animation: wpgen-spin 1s linear infinite;
}

@keyframes wpgen-spin {
    to { transform: rotate(360deg); }
}
"""
        (css_dir / "preloader.css").write_text(preloader_css, encoding="utf-8")

        # JS for preloader
        preloader_js = """(function() {
    'use strict';

    // Create preloader element
    const preloader = document.createElement('div');
    preloader.className = 'wpgen-preloader';
    preloader.innerHTML = '<div class="wpgen-preloader-logo"></div>';
    document.body.insertBefore(preloader, document.body.firstChild);

    // Hide preloader when page is loaded
    window.addEventListener('load', function() {
        setTimeout(function() {
            preloader.classList.add('fade-out');
            setTimeout(function() {
                preloader.remove();
            }, 500);
        }, 500);
    });

    // Fallback: hide after 3 seconds max
    setTimeout(function() {
        if (preloader.parentNode) {
            preloader.classList.add('fade-out');
            setTimeout(function() {
                if (preloader.parentNode) {
                    preloader.remove();
                }
            }, 500);
        }
    }, 3000);
})();
"""
        (js_dir / "preloader.js").write_text(preloader_js, encoding="utf-8")
        logger.info("Generated animated preloader")

    def _generate_readme(self, theme_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate README.md for the theme.

        Args:
            theme_dir: Theme directory path
            requirements: Theme requirements
        """
        logger.info("Generating README.md")

        readme_content = f"""# {requirements['theme_display_name']}

{requirements['description']}

## Description

This WordPress theme was automatically generated using WPGen.

## Features

{chr(10).join(f'- {feature}' for feature in requirements.get('features', []))}

## Installation

1. Download the theme ZIP file
2. In WordPress admin, go to Appearance > Themes > Add New > Upload Theme
3. Choose the ZIP file and click Install Now
4. After installation, click Activate

## Development

This theme was generated with the following specifications:

- **Color Scheme**: {requirements.get('color_scheme', 'default')}
- **Layout**: {requirements.get('layout', 'full-width')}
- **Pages**: {', '.join(requirements.get('pages', []))}

## Customization

You can customize this theme using:

1. WordPress Customizer (Appearance > Customize)
2. Editing the theme files directly
3. Using a child theme (recommended for major modifications)

## Support

For issues and questions:
- Check the [WordPress Codex](https://codex.wordpress.org/)
- Visit [WordPress Support Forums](https://wordpress.org/support/)

## License

This theme is licensed under {self.config.get('license', 'GPL-2.0-or-later')}.

## Credits

- Generated by: WPGen
- Generated on: {datetime.now().strftime('%Y-%m-%d')}
"""

        readme_file = theme_dir / "README.md"
        readme_file.write_text(readme_content, encoding="utf-8")
        logger.info("Generated README.md successfully")

    def _generate_gitignore(self, theme_dir: Path) -> None:
        """Generate .gitignore file for the theme.

        Args:
            theme_dir: Theme directory path
        """
        logger.info("Generating .gitignore")

        gitignore_content = """# WordPress
wp-config.php
wp-content/uploads/
wp-content/cache/
wp-content/backup-db/

# Theme development
node_modules/
*.sass-cache/
.DS_Store
Thumbs.db
*.log

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# Build files
dist/
build/
"""

        gitignore_file = theme_dir / ".gitignore"
        gitignore_file.write_text(gitignore_content, encoding="utf-8")
        logger.info("Generated .gitignore successfully")

    def _generate_wp_config(self, output_dir: Path, requirements: Dict[str, Any]) -> None:
        """Generate sample wp-config.php file.

        Args:
            output_dir: Output directory (parent of theme dir)
            requirements: Theme requirements
        """
        logger.info("Generating wp-config-sample.php")

        wp_config_content = """<?php
/**
 * Sample WordPress Configuration File
 *
 * This file contains sample configuration for WordPress.
 * Copy this file to 'wp-config.php' and fill in the values.
 *
 * @package WordPress
 */

// ** Database settings ** //
define( 'DB_NAME', 'database_name_here' );
define( 'DB_USER', 'username_here' );
define( 'DB_PASSWORD', 'password_here' );
define( 'DB_HOST', 'localhost' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

// ** Authentication unique keys and salts ** //
// Get these from: https://api.wordpress.org/secret-key/1.1/salt/
define( 'AUTH_KEY',         'put your unique phrase here' );
define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
define( 'LOGGED_IN_KEY',    'put your unique phrase here' );
define( 'NONCE_KEY',        'put your unique phrase here' );
define( 'AUTH_SALT',        'put your unique phrase here' );
define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
define( 'LOGGED_IN_SALT',   'put your unique phrase here' );
define( 'NONCE_SALT',       'put your unique phrase here' );

// ** WordPress database table prefix ** //
$table_prefix = 'wp_';

// ** WordPress debugging mode ** //
define( 'WP_DEBUG', false );

/* That's all, stop editing! Happy publishing. */

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
"""

        wp_config_file = output_dir / "wp-config-sample.php"
        wp_config_file.write_text(wp_config_content, encoding="utf-8")
        logger.info("Generated wp-config-sample.php successfully")
